DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM AUD ORDER BY DATE;
DROP TABLE AUD;
CREATE TABLE AUD AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM CNY ORDER BY DATE;
DROP TABLE CNY;
CREATE TABLE CNY AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM EUR ORDER BY DATE;
DROP TABLE EUR;
CREATE TABLE EUR AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM GBP ORDER BY DATE;
DROP TABLE GBP;
CREATE TABLE GBP AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM HKD ORDER BY DATE;
DROP TABLE HKD;
CREATE TABLE HKD AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM IDR ORDER BY DATE;
DROP TABLE IDR;
CREATE TABLE IDR AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM PHP ORDER BY DATE;
DROP TABLE PHP;
CREATE TABLE PHP AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM SGD ORDER BY DATE;
DROP TABLE SGD;
CREATE TABLE SGD AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM THB ORDER BY DATE;
DROP TABLE THB;
CREATE TABLE THB AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM TWD ORDER BY DATE;
DROP TABLE TWD;
CREATE TABLE TWD AS SELECT * FROM temp;
DROP TABLE temp;
--
CREATE TABLE temp AS select distinct * FROM USD ORDER BY DATE;
DROP TABLE USD;
CREATE TABLE USD AS SELECT * FROM temp;
DROP TABLE temp;
